/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Viceleno
 */
public class fMenus extends javax.swing.JFrame {

    /**
     * Creates new form fMenus
     */
    public fMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        usuarioCadastrar = new javax.swing.JMenuItem();
        usuarioExcluir = new javax.swing.JMenuItem();
        usuarioAlterar = new javax.swing.JMenuItem();
        usuarioPesquisar = new javax.swing.JMenuItem();
        menuLaboratorio = new javax.swing.JMenu();
        laboratorioCadastrar = new javax.swing.JMenuItem();
        laboratorioExcluir = new javax.swing.JMenuItem();
        laboratorioAlterar = new javax.swing.JMenuItem();
        laboratorioPesquisar = new javax.swing.JMenuItem();
        menuSituacao = new javax.swing.JMenu();
        miReservas = new javax.swing.JMenuItem();
        miReservarLab = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendador360");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        menuUsuario.setText("Usuario");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });

        usuarioCadastrar.setText("Cadastrar");
        usuarioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCadastrarActionPerformed(evt);
            }
        });
        menuUsuario.add(usuarioCadastrar);

        usuarioExcluir.setText("Excluir");
        usuarioExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioExcluirActionPerformed(evt);
            }
        });
        menuUsuario.add(usuarioExcluir);

        usuarioAlterar.setText("Alterar");
        usuarioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioAlterarActionPerformed(evt);
            }
        });
        menuUsuario.add(usuarioAlterar);

        usuarioPesquisar.setText("Pesquisar");
        usuarioPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioPesquisarActionPerformed(evt);
            }
        });
        menuUsuario.add(usuarioPesquisar);

        barraMenu.add(menuUsuario);

        menuLaboratorio.setText("Laboratorio");
        menuLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaboratorioActionPerformed(evt);
            }
        });

        laboratorioCadastrar.setText("Cadastrar");
        laboratorioCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioCadastrarActionPerformed(evt);
            }
        });
        menuLaboratorio.add(laboratorioCadastrar);

        laboratorioExcluir.setText("Excluir");
        laboratorioExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioExcluirActionPerformed(evt);
            }
        });
        menuLaboratorio.add(laboratorioExcluir);

        laboratorioAlterar.setText("Alterar");
        laboratorioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioAlterarActionPerformed(evt);
            }
        });
        menuLaboratorio.add(laboratorioAlterar);

        laboratorioPesquisar.setText("Pesquisar");
        laboratorioPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioPesquisarActionPerformed(evt);
            }
        });
        menuLaboratorio.add(laboratorioPesquisar);

        barraMenu.add(menuLaboratorio);

        menuSituacao.setText("Situação");
        menuSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSituacaoActionPerformed(evt);
            }
        });

        miReservas.setText("Reservas");
        miReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReservasActionPerformed(evt);
            }
        });
        menuSituacao.add(miReservas);

        miReservarLab.setText("Reservar Laboratorio");
        miReservarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miReservarLabActionPerformed(evt);
            }
        });
        menuSituacao.add(miReservarLab);

        barraMenu.add(menuSituacao);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCadastrarActionPerformed
        internalFrameCadastrar cadastrarUsuario = new internalFrameCadastrar();
            jDesktopPane1.add(cadastrarUsuario);
            cadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioCadastrarActionPerformed

    private void usuarioExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioExcluirActionPerformed
        internalFrameExcluir excluirUsuario = new internalFrameExcluir();
            jDesktopPane1.add(excluirUsuario);
            excluirUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioExcluirActionPerformed

    private void laboratorioExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioExcluirActionPerformed
        internalFrameExcluirLab excluirlaboratorio = new internalFrameExcluirLab();
            jDesktopPane1.add(excluirlaboratorio);
            excluirlaboratorio.setVisible(true);
    }//GEN-LAST:event_laboratorioExcluirActionPerformed

    private void usuarioPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioPesquisarActionPerformed
        internalFramePesquisar pesquisarUsuario = new internalFramePesquisar();
            jDesktopPane1.add(pesquisarUsuario);
            pesquisarUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioPesquisarActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void usuarioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioAlterarActionPerformed
        internalFrameAlterar alterarUsuario = new internalFrameAlterar();
            jDesktopPane1.add(alterarUsuario);
            alterarUsuario.setVisible(true);
    }//GEN-LAST:event_usuarioAlterarActionPerformed

    private void menuLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaboratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLaboratorioActionPerformed

    private void laboratorioCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioCadastrarActionPerformed
        internalFrameCadastrarLab cadastroLaboratorio = new internalFrameCadastrarLab();
            jDesktopPane1.add(cadastroLaboratorio);
            cadastroLaboratorio.setVisible(true);
    }//GEN-LAST:event_laboratorioCadastrarActionPerformed

    private void laboratorioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioAlterarActionPerformed
        internalFrameAlterarLab alterarLaboratorio = new internalFrameAlterarLab();
            jDesktopPane1.add(alterarLaboratorio);
            alterarLaboratorio.setVisible(true);
    }//GEN-LAST:event_laboratorioAlterarActionPerformed

    private void laboratorioPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioPesquisarActionPerformed
        internalFramePesquisarLab pesquisarLaboratorio = new internalFramePesquisarLab();
            jDesktopPane1.add(pesquisarLaboratorio);
            pesquisarLaboratorio.setVisible(true);
    }//GEN-LAST:event_laboratorioPesquisarActionPerformed

    private void miReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReservasActionPerformed
        internalFrameReservas reservas = new internalFrameReservas();
            jDesktopPane1.add(reservas);
            reservas.setVisible(true);
    }//GEN-LAST:event_miReservasActionPerformed

    private void menuSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSituacaoActionPerformed
        
    }//GEN-LAST:event_menuSituacaoActionPerformed

    private void miReservarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miReservarLabActionPerformed
        internalFrameReservarLab reservaLab = new internalFrameReservarLab();
            jDesktopPane1.add(reservaLab);
            reservaLab.setVisible(true);
    }//GEN-LAST:event_miReservarLabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem laboratorioAlterar;
    private javax.swing.JMenuItem laboratorioCadastrar;
    private javax.swing.JMenuItem laboratorioExcluir;
    private javax.swing.JMenuItem laboratorioPesquisar;
    private javax.swing.JMenu menuLaboratorio;
    private javax.swing.JMenu menuSituacao;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem miReservarLab;
    private javax.swing.JMenuItem miReservas;
    private javax.swing.JMenuItem usuarioAlterar;
    private javax.swing.JMenuItem usuarioCadastrar;
    private javax.swing.JMenuItem usuarioExcluir;
    private javax.swing.JMenuItem usuarioPesquisar;
    // End of variables declaration//GEN-END:variables
}
