/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Viceleno
 */
public class internalFrameCadastrarLab extends javax.swing.JInternalFrame {

    /**
     * Creates new form internalFrameCadastrarLab
     */
    public internalFrameCadastrarLab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDadosLab = new javax.swing.JPanel();
        tfNomeLab = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        lSobrenome = new javax.swing.JLabel();
        tfCapacidadeLab = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        bCadastrarLab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFinalidadeLab = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        panelDadosLab.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Laboratório"));

        lNome.setForeground(new java.awt.Color(51, 0, 204));
        lNome.setText("Nome");

        lSobrenome.setForeground(new java.awt.Color(51, 0, 204));
        lSobrenome.setText("Capacidade");

        tfCapacidadeLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCapacidadeLabActionPerformed(evt);
            }
        });

        lEmail.setForeground(new java.awt.Color(51, 0, 204));
        lEmail.setText("Finalidade");

        bCadastrarLab.setText("Cadastrar");
        bCadastrarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarLabActionPerformed(evt);
            }
        });

        taFinalidadeLab.setColumns(20);
        taFinalidadeLab.setRows(5);
        jScrollPane1.setViewportView(taFinalidadeLab);

        javax.swing.GroupLayout panelDadosLabLayout = new javax.swing.GroupLayout(panelDadosLab);
        panelDadosLab.setLayout(panelDadosLabLayout);
        panelDadosLabLayout.setHorizontalGroup(
            panelDadosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDadosLabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelDadosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDadosLabLayout.createSequentialGroup()
                        .addComponent(lEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDadosLabLayout.createSequentialGroup()
                        .addComponent(lNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(277, 277, 277))
                    .addComponent(tfCapacidadeLab, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDadosLabLayout.createSequentialGroup()
                        .addComponent(lSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(268, 268, 268))
                    .addComponent(tfNomeLab, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosLabLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bCadastrarLab, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        panelDadosLabLayout.setVerticalGroup(
            panelDadosLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosLabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCapacidadeLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCadastrarLab)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDadosLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelDadosLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCapacidadeLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCapacidadeLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCapacidadeLabActionPerformed

    private void bCadastrarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCadastrarLabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrarLab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lSobrenome;
    private javax.swing.JPanel panelDadosLab;
    private javax.swing.JTextArea taFinalidadeLab;
    private javax.swing.JTextField tfCapacidadeLab;
    private javax.swing.JTextField tfNomeLab;
    // End of variables declaration//GEN-END:variables
}
